const SUNNSTEEL_CACHE_PREFIX = 'ss-'
const ACTIVE_WORKOUT_SESSION_PREFIX = '/workouts/sessions/'

export const isSunnsteelCacheName = (cacheName: string): boolean =>
	cacheName.startsWith(SUNNSTEEL_CACHE_PREFIX)

export const shouldDeferServiceWorkerUpdate = (pathname: string): boolean =>
	pathname.startsWith(ACTIVE_WORKOUT_SESSION_PREFIX)

// TD-44 -----------------------------------------------------------------------
//
// The worker is generated by Serwist at build time (worker/sw.ts). These rules
// are the application's own policy, kept here so the worker and the tests read
// the same thing.

/**
 * Prefix for every cache the generated worker owns (`ss-precache-v2-…`,
 * `ss-pages`, `ss-assets`), so development cleanup and `isSunnsteelCacheName`
 * keep matching them.
 */
export const SERVICE_WORKER_CACHE_ID = 'ss'
export const PAGE_CACHE_NAME = 'ss-pages'
export const ASSET_CACHE_NAME = 'ss-assets'

/** Precached at build time and served when a page is neither online nor cached. */
export const OFFLINE_PAGE_URL = '/offline'

/**
 * The hand-written worker's namespaces (`ss-runtime-v6`, `ss-precache-v6`,
 * `ss-pages-v6` and older). Deleted when the generated worker activates; the
 * generated worker's own names never match, and neither does another app's.
 */
export const isLegacyWorkerCache = (cacheName: string): boolean =>
	/^ss-(?:runtime|precache|pages)-v\d+$/.test(cacheName)

const STATIC_ASSET =
	/\.(?:js|css|png|jpg|jpeg|gif|svg|webp|ico|woff2?|ttf|otf)$/i

const isNeverCached = (url: URL, origin: string): boolean =>
	url.origin !== origin ||
	url.pathname.startsWith('/api/') ||
	// OAuth callbacks carry one-time codes in the URL; a copy is worthless and
	// the code should not sit in Cache Storage.
	url.pathname.startsWith('/auth/')

export const isNavigationRequest = (request: {
	mode: string
	destination: string
}): boolean => request.mode === 'navigate' || request.destination === 'document'

/**
 * Pages are kept network-first so a stale page never pins a stale bundle; the
 * copy is only for going offline. Backend, cross-origin and auth-callback
 * responses are never cached.
 */
export const isCacheablePage = (url: URL, origin: string): boolean =>
	!isNeverCached(url, origin)

/** Same-origin files by extension; Next.js build chunks arrive precached. */
export const isCacheableStaticAsset = (url: URL, origin: string): boolean =>
	!isNeverCached(url, origin) && STATIC_ASSET.test(url.pathname)
