import type { CSSProperties } from 'react'

import {
	isRenaissanceRankId,
	rankCrestTier,
	type RenaissanceRankId,
} from './rank-identity'

/**
 * ACH-11 (design system §24). A member's rank dresses their own profile
 * header, and only that: the rank they hold, only when the viewer may see it
 * (ACH-10's Rank privacy row decides that before the rank ever reaches the
 * page). Each rank is richer than the one below it; the ornament itself is
 * generated by scripts/generate-rank-decoration.mjs.
 */
export type RankDecorationSlug =
	'initiate' | 'apprentice' | 'artisan' | 'maestro' | 'virtuoso' | 'laureate'

export interface RankDecoration {
	rankId: RenaissanceRankId
	/** 0 for Initiate up to 5 for Laureate, in ladder order. */
	tier: number
	slug: RankDecorationSlug
	/** Artisan and above turn the header into a framed panel. */
	framed: boolean
	/** The custom properties the header section carries (globals.css). */
	style: CSSProperties
}

/** The frame's draw in ms: the rule draw at Initiate, longer up the ladder. */
export const RANK_DECORATION_DRAW_MS = [240, 360, 420, 480, 520, 600] as const

/**
 * The ground each rank's ornament is cut into: the page ground for the two
 * ranks without a panel, the sunk vault for Virtuoso, the surface otherwise.
 */
export const RANK_DECORATION_GROUND = [
	'var(--background)',
	'var(--background)',
	'var(--surface)',
	'var(--surface)',
	'var(--surface-sunk)',
	'var(--surface)',
] as const

/** Opacity of the ground pattern in Day and in Night (§24.3). */
export const RANK_GROUND_OPACITY = {
	day: [0, 0, 0.16, 0.11, 0.2, 0.1],
	night: [0, 0, 0.2, 0.15, 0.3, 0.13],
} as const

/**
 * The decoration for the rank a profile header shows, or null when it shows
 * none (no rank yet, a rank the viewer may not see, or an ID the ladder does
 * not know). Keyed by the stable rank ID, never by title (§19.2 rule 6).
 */
export function rankDecoration(
	rank: { id: string } | null | undefined,
): RankDecoration | null {
	if (!rank || !isRenaissanceRankId(rank.id)) return null
	const tier = rankCrestTier(rank.id)
	const slug = rank.id.toLowerCase() as RankDecorationSlug
	const pigment = `var(--rank-${slug})`
	return {
		rankId: rank.id,
		tier,
		slug,
		framed: tier >= 2,
		style: {
			'--rank-pigment': pigment,
			'--rank-cut': RANK_DECORATION_GROUND[tier],
			'--rank-draw': `${RANK_DECORATION_DRAW_MS[tier]}ms`,
			'--rank-ground-day': String(RANK_GROUND_OPACITY.day[tier]),
			'--rank-ground-night': String(RANK_GROUND_OPACITY.night[tier]),
			'--corner-bracket': pigment,
		} as CSSProperties,
	}
}
